### ISSUE TITLE
[FeatureRequest] Open edited file

### ISSUE THREAD

**Issue by hunhejj** [madskristensen/OpenInVsCode#19]
Can you extend this awesome tool to open the currently opened file?  
This would be my use case:
1) edit a file in Visual Studio (not the one highlighted in the Solution Explorer!)
2) press a keyboard shortcut
3) open the same file in Visual Studio Code - without modifying what is selected in the Solution Explorer
Preferably with passing the $CurrentLine and the $CurrentColumn as arguments so you end up at the exact same location as you were in Visual Studio before.

**Comment by cblech** [comment]
I've opened a Pull Request for that (#32)
