### ISSUE TITLE
Keyboard shortcut?

### ISSUE THREAD

**Issue by robomojo** [madskristensen/OpenInVsCode#4]
Hi - This is great. How can I assign it to a keyboard shortcut? From editing a file, I currently I need to do the "Ctrl+[, S", F10, Down, Down, Down, Enter :)

**Comment by madskristensen** [comment]
You can set the keyboard shortcut in _Tools -> Options -> Environment -> Keyboard_ by searching for "visualstudiocode" and then set your desired shortcut for it

**Comment by robomojo** [comment]
I see - I bound another key to Sync the solution explorer with active document. So now I just Alt + S to sync, and then Alt + Q to open in code. Thanks!
